//
//  Metrics.swift
//  Bartleby
//
// THIS FILE AS BEEN GENERATED BY BARTLEBYFLEXIONS for Benoit Pereira da Silva https://pereira-da-silva.com/contact
// DO NOT MODIFY THIS FILE YOUR MODIFICATIONS WOULD BE ERASED ON NEXT GENERATION!
//
// Copyright (c) 2016  https://bartlebys.org  All rights reserved.
//

import Foundation

#if os(macOS) && USE_COCOA_BINDINGS
public typealias Metrics = DynamicMetrics
#else
public typealias Metrics = CommonMetrics
#endif

// MARK: Bartleby's Core: a value object used to record metrics
open class CommonMetrics : Model, Payload, Result{

    public typealias CollectedType = Metrics

	//The action name e.g: UpdateUser
	open var operationName:String = Default.NO_NAME

	//The associated url
	open var associatedURL:URL?

	//The elasped time since app started up.
	open var elapsed:Double = 0

	//The time interval in seconds from the time the request started to the time the request completed.
	open var requestDuration:Double = 0

	// The time interval in seconds from the time the request completed to the time response serialization completed.
	open var serializationDuration:Double = 0

	//the verification method
	public enum StreamOrientation:String{
		case upStream = "upStream"
		case downStream = "downStream"
	}
	open var streamOrientation:StreamOrientation = .upStream


    // MARK: - Codable


    public enum MetricsCodingKeys: String,CodingKey{
		case operationName
		case associatedURL
		case elapsed
		case requestDuration
		case serializationDuration
		case streamOrientation
    }

    required public init(from decoder: Decoder) throws{
		try super.init(from: decoder)
        try self.quietThrowingChanges {
			let values = try decoder.container(keyedBy: MetricsCodingKeys.self)
			self.operationName = try values.decode(String.self,forKey:.operationName)
			self.associatedURL = try values.decodeIfPresent(URL.self,forKey:.associatedURL)
			self.elapsed = try values.decode(Double.self,forKey:.elapsed)
			self.requestDuration = try values.decode(Double.self,forKey:.requestDuration)
			self.serializationDuration = try values.decode(Double.self,forKey:.serializationDuration)
			self.streamOrientation = Metrics.StreamOrientation(rawValue: try values.decode(String.self,forKey:.streamOrientation)) ?? .upStream
        }
    }

    override open func encode(to encoder: Encoder) throws {
		try super.encode(to:encoder)
		var container = encoder.container(keyedBy: MetricsCodingKeys.self)
		try container.encode(self.operationName,forKey:.operationName)
		try container.encodeIfPresent(self.associatedURL,forKey:.associatedURL)
		try container.encode(self.elapsed,forKey:.elapsed)
		try container.encode(self.requestDuration,forKey:.requestDuration)
		try container.encode(self.serializationDuration,forKey:.serializationDuration)
		try container.encode(self.streamOrientation.rawValue ,forKey:.streamOrientation)
    }



    // MARK: - Initializable

    required public init() {
        super.init()
    }

    // MARK: - UniversalType

    override  open class var typeName:String{
        return "Metrics"
    }

    override  open class var collectionName:String{
        return "metrics"
    }

    override  open var d_collectionName:String{
        return Metrics.collectionName
    }


    // MARK: - NSCopy aka CopyingProtocol

    /// Provides an unregistered copy (the instance is not held by the dataPoint)
    ///
    /// - Parameter zone: the zone
    /// - Returns: the copy
    override open func copy(with zone: NSZone? = nil) -> Any {
        guard let data = try? JSON.encoder.encode(self) else {
            return ObjectError.message(message: "Encoding issue on copy of: \(Metrics.typeName) \(self.uid)")
        }
        guard let copy = try? JSON.decoder.decode(type(of:self), from: data) else {
            return ObjectError.message(message: "Decoding issue on copy of:\(Metrics.typeName) \(self.uid)")
        }
        return copy
    }
}



#if os(macOS) && USE_COCOA_BINDINGS

// You Can use Dynamic Override to support Cocoa Bindings
// This class can be used in a CollectionOf<T>

@objc open class DynamicMetrics:CommonMetrics{

    @objc override dynamic open var  operationName : String{
        set{ super.operationName = newValue }
        get{ return super.operationName }
    }

    @objc override dynamic open var  associatedURL : URL?{
        set{ super.associatedURL = newValue }
        get{ return super.associatedURL }
    }

    @objc override dynamic open var  elapsed : Double{
        set{ super.elapsed = newValue }
        get{ return super.elapsed }
    }

    @objc override dynamic open var  requestDuration : Double{
        set{ super.requestDuration = newValue }
        get{ return super.requestDuration }
    }

    @objc override dynamic open var  serializationDuration : Double{
        set{ super.serializationDuration = newValue }
        get{ return super.serializationDuration }
    }
}

#endif
